const Products = [
    {id: 1,
    title: "Máscara de Pestañas",
    price: "2599",
    description: "La máscara de pestañas más vendida de Glossier alarga y levanta visiblemente las pestañas (sin manchas ni escamas) para un efecto de extensiones.",
    pictureURL: "https://images.ctfassets.net/p3w8f4svwgcg/73knH7ZY9CGyqLrgZEbvYs/8baba45f86debd471bf5c4a6e6f24703/lashslick-portrait__1_.jpg?w=1400&q=80&fm=webp",
    stock: 3,
    categoryID: 1,
    },
    {id: 2,
    title: "Delineador de ojos",
    price: "2599",
    description: "Un delineador de ojos líquido negro fácil de usar con punta de pincel para una definición precisa, en una fórmula resistente.",
    pictureURL: "https://images.ctfassets.net/p3w8f4svwgcg/1yIk4nmjI4xFLG5Vb5ve6X/cdba9732b9f274b3049f3040802498eb/1__2_.png?w=1400&q=80&fm=webp",
    stock: 5,
    categoryID: 1,
    },
    {id: 3,
    title: "Labial matte Generation G de Glossier",
    price: "2599",
    description: "El nuevo labial de la Marca Glossier da el aspecto y el acabado de un lápiz labial recién borrado, desgastado. La formula construible se desliza facil y uniformemente, sin necesidad de espejo.",
    pictureURL: "https://images.ctfassets.net/p3w8f4svwgcg/3zdGoeX0mbYs4nGYz6PtN6/0c44dd4dd66c3a81ea6dac3601d280b5/Global_-_GenG_-_1.jpg?w=1400&q=80&fm=webp",
    stock: 8,
    categoryID: 1,
    },
    {id: 4,
    title: "Prebase Hidratante",
    price: "3608,50",
    description: "La crema ligera en gel equilibra la grasa sin resecar la piel ni dejar un acabado plano y con polvo. Los poros parecen minimizados, el brillo desaparece y la piel está hidratada y feliz",
    pictureURL: "https://images.ctfassets.net/p3w8f4svwgcg/7y2VRfdXXQf9rySHPKu0F9/47de8552406c70ff12842d99c2ebf4e6/PMB_1.jpg?w=1400&q=80&fm=webp",
    stock: 10,
    categoryID: 2,
    },
    {id: 5,
    title: "Crema para pieles secas",
    price: "4042",
    description: "Una crema reparadora de Glossier para pieles muy secas y/o sensibles, especialmente después de la exposición al clima frío, sol intenso, exfoliación excesiva y más.",
    pictureURL: "https://images.ctfassets.net/p3w8f4svwgcg/37toJ1HXD5t4WEkOJcRg88/bdb82986da621aecf0f949ddd8d290ef/AfterBaume_PDP_2.jpg?w=1400&q=80&fm=webp",
    stock: 10,
    categoryID: 2,
    }
]

export default Products